//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace WebApplication
{
    public partial class Category
    {
        public Category()
        {
            this.Entries = new HashSet<Entry>();
        }
    
        public int Id { get; set; }
        public string huTitle { get; set; }
        public string enTitle { get; set; }
    
        public virtual ICollection<Entry> Entries { get; set; }
    }
    
}
