//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entry
    {
        public Entry()
        {
            this.Categories = new HashSet<Category>();
            this.Keywords = new HashSet<Keyword>();
            this.Files = new HashSet<File>();
        }
    
        public int Id { get; set; }
        public string huTitle { get; set; }
        public string enTitle { get; set; }
        public bool Published { get; set; }
        public System.DateTime PublishedDate { get; set; }
        public string huContent { get; set; }
        public string enContent { get; set; }
        public int UserId { get; set; }
        public string huIntroduction { get; set; }
        public string enIntroduction { get; set; }
    
        public virtual User Creator { get; set; }
        public virtual ICollection<Category> Categories { get; set; }
        public virtual ICollection<Keyword> Keywords { get; set; }
        public virtual ICollection<File> Files { get; set; }
    }
}
