//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeedBack
    {
        public int Id { get; set; }
        public string Message { get; set; }
        public string EmailAddress { get; set; }
        public System.DateTime SendDate { get; set; }
        public bool Checked { get; set; }
    }
}
