//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace WebApplication
{
    public partial class File
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Location { get; set; }
        public int EntryId { get; set; }
    
        public virtual Entry Entry { get; set; }
    }
    
}
