//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Page
    {
        public int Id { get; set; }
        public string huTitle { get; set; }
        public string enTitle { get; set; }
        public bool Published { get; set; }
        public string huContent { get; set; }
        public string enContent { get; set; }
        public int UserId { get; set; }
    
        public virtual User Creator { get; set; }
    }
}
