//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace WebApplication
{
    public partial class User
    {
        public User()
        {
            this.MyEntries = new HashSet<Entry>();
            this.MyPages = new HashSet<Page>();
            this.Comments = new HashSet<Comment>();
        }
    
        public int Id { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public int Type { get; set; }
        public string ActivationCode { get; set; }
        public bool IsActivated { get; set; }
        public System.DateTime RegistrationDate { get; set; }
        public string EmailAddress { get; set; }
        public string CookieHash { get; set; }
    
        public virtual ICollection<Entry> MyEntries { get; set; }
        public virtual ICollection<Page> MyPages { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }
    }
    
}
