//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Common {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebApplication.Resources.Common", typeof(Common).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Az activációs emailt elküldtük a megadott címre..
        /// </summary>
        public static string ActivationSent {
            get {
                return ResourceManager.GetString("ActivationSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adminisztráció.
        /// </summary>
        public static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adminisztrátor.
        /// </summary>
        public static string Administrator {
            get {
                return ResourceManager.GetString("Administrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publikálva  van.
        /// </summary>
        public static string AlreadyPublished {
            get {
                return ResourceManager.GetString("AlreadyPublished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Csatolmányok.
        /// </summary>
        public static string Attachment {
            get {
                return ResourceManager.GetString("Attachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vissza a listához.
        /// </summary>
        public static string BackToList {
            get {
                return ResourceManager.GetString("BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fel a tetejére.
        /// </summary>
        public static string BackToTheTop {
            get {
                return ResourceManager.GetString("BackToTheTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alap adatok.
        /// </summary>
        public static string BasicData {
            get {
                return ResourceManager.GetString("BasicData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mégse.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategóriák.
        /// </summary>
        public static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategória.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email címed cseréje.
        /// </summary>
        public static string ChangeEmail {
            get {
                return ResourceManager.GetString("ChangeEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change language.
        /// </summary>
        public static string ChangeLanguage {
            get {
                return ResourceManager.GetString("ChangeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jelszavad cseréje.
        /// </summary>
        public static string ChangePass {
            get {
                return ResourceManager.GetString("ChangePass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kommentedet töröltük..
        /// </summary>
        public static string CommentDeleted {
            get {
                return ResourceManager.GetString("CommentDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ide írhatod az üzenetedet....
        /// </summary>
        public static string CommentPlaceholder {
            get {
                return ResourceManager.GetString("CommentPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kommentek.
        /// </summary>
        public static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kommentedet feltöltöttük..
        /// </summary>
        public static string CommentSend {
            get {
                return ResourceManager.GetString("CommentSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jelszó újra.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A két jelszó nem egyezik meg.
        /// </summary>
        public static string ConfirmPasswordValidation {
            get {
                return ResourceManager.GetString("ConfirmPasswordValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tartalom.
        /// </summary>
        public static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Létrehozás.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Létrehozta.
        /// </summary>
        public static string CreatedBy {
            get {
                return ResourceManager.GetString("CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magyar.
        /// </summary>
        public static string CurrentLanguageName {
            get {
                return ResourceManager.GetString("CurrentLanguageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dátum.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Törlés.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biztos benne, hogy szeretné ezt törölni?.
        /// </summary>
        public static string DeleteConfirm {
            get {
                return ResourceManager.GetString("DeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Részletek.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szerkesztés.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email cím.
        /// </summary>
        public static string EmailAddress {
            get {
                return ResourceManager.GetString("EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Az email címed megváltozott..
        /// </summary>
        public static string EmailChanged {
            get {
                return ResourceManager.GetString("EmailChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Az email cím nem megfelelő.
        /// </summary>
        public static string EmailValidation {
            get {
                return ResourceManager.GetString("EmailValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bejegyzések.
        /// </summary>
        public static string Entries {
            get {
                return ResourceManager.GetString("Entries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bejegyzés.
        /// </summary>
        public static string Entry {
            get {
                return ResourceManager.GetString("Entry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoppá, ez itt hiba üzenet!.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Egy hiba keletkezett az adatbázisban. Kérlek később próbáld meg újra..
        /// </summary>
        public static string ErrorDatabase {
            get {
                return ResourceManager.GetString("ErrorDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kiemelt bejegyzések.
        /// </summary>
        public static string FeaturedEntries {
            get {
                return ResourceManager.GetString("FeaturedEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kiemelt részhez.
        /// </summary>
        public static string FeaturedPart {
            get {
                return ResourceManager.GetString("FeaturedPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visszajelzések.
        /// </summary>
        public static string Feedbacks {
            get {
                return ResourceManager.GetString("Feedbacks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elfelejtett jelszó.
        /// </summary>
        public static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kezdőlap.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kép.
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Információ.
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktiválva.
        /// </summary>
        public static string IsActivated {
            get {
                return ResourceManager.GetString("IsActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kulcsszavak.
        /// </summary>
        public static string Keywords {
            get {
                return ResourceManager.GetString("Keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szint.
        /// </summary>
        public static string Level {
            get {
                return ResourceManager.GetString("Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bejelentkezés.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bejelentkezve, mint.
        /// </summary>
        public static string LoginAs {
            get {
                return ResourceManager.GetString("LoginAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Belépés.
        /// </summary>
        public static string LoginButton {
            get {
                return ResourceManager.GetString("LoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sikeresen bejelentkeztél..
        /// </summary>
        public static string LoginMessage {
            get {
                return ResourceManager.GetString("LoginMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kijelentkezés.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sikeresen kijelentkezett..
        /// </summary>
        public static string LogoutMessage {
            get {
                return ResourceManager.GetString("LogoutMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to További bejegyzések.
        /// </summary>
        public static string MoreEntries {
            get {
                return ResourceManager.GetString("MoreEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Új email cím.
        /// </summary>
        public static string NewEmail {
            get {
                return ResourceManager.GetString("NewEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Olvasatlan üzenetek.
        /// </summary>
        public static string NewMessages {
            get {
                return ResourceManager.GetString("NewMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Az új jelszavadat emailben elküldtük..
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Új jelszó.
        /// </summary>
        public static string NewPw {
            get {
                return ResourceManager.GetString("NewPw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nincs megjelenítendő elem.
        /// </summary>
        public static string NoElement {
            get {
                return ResourceManager.GetString("NoElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nincs találat..
        /// </summary>
        public static string NoResult {
            get {
                return ResourceManager.GetString("NoResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A fájlok letöltéséhez előbb jelentkezz be..
        /// </summary>
        public static string NotPermissionAttachments {
            get {
                return ResourceManager.GetString("NotPermissionAttachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Komment küldéséhez be kell jelentkezned az oldalra..
        /// </summary>
        public static string NotPermissionComment {
            get {
                return ResourceManager.GetString("NotPermissionComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nincs joga erre a területre lépni!.
        /// </summary>
        public static string NotPermisson {
            get {
                return ResourceManager.GetString("NotPermisson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nincs publikálva.
        /// </summary>
        public static string NotPublished {
            get {
                return ResourceManager.GetString("NotPublished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Olvasott üzenetek.
        /// </summary>
        public static string OldMessages {
            get {
                return ResourceManager.GetString("OldMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Régi jelszó.
        /// </summary>
        public static string OldPw {
            get {
                return ResourceManager.GetString("OldPw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eredeti.
        /// </summary>
        public static string Original {
            get {
                return ResourceManager.GetString("Original", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ...vagy Regisztrálj!.
        /// </summary>
        public static string OrRegister {
            get {
                return ResourceManager.GetString("OrRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en.
        /// </summary>
        public static string OtherLanguageKey {
            get {
                return ResourceManager.GetString("OtherLanguageKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string OtherLanguageName {
            get {
                return ResourceManager.GetString("OtherLanguageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oldal.
        /// </summary>
        public static string Page {
            get {
                return ResourceManager.GetString("Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oldalak.
        /// </summary>
        public static string Pages {
            get {
                return ResourceManager.GetString("Pages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jelszó.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A jelszónak legalább 6 karakternek kell lennie.
        /// </summary>
        public static string PasswordValidation {
            get {
                return ResourceManager.GetString("PasswordValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publikálás.
        /// </summary>
        public static string Publish {
            get {
                return ResourceManager.GetString("Publish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publikálva van.
        /// </summary>
        public static string Published {
            get {
                return ResourceManager.GetString("Published", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A jelszó megváltozott..
        /// </summary>
        public static string PwChanged {
            get {
                return ResourceManager.GetString("PwChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Olvasó.
        /// </summary>
        public static string Reader {
            get {
                return ResourceManager.GetString("Reader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regisztráció.
        /// </summary>
        public static string Registration {
            get {
                return ResourceManager.GetString("Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to emlékezz rám.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kötelező.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mentés.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keresés.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Küldés.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beállítás kiemelt.
        /// </summary>
        public static string SetFeatured {
            get {
                return ResourceManager.GetString("SetFeatured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oldaltérkép.
        /// </summary>
        public static string Sitemap {
            get {
                return ResourceManager.GetString("Sitemap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Közzösségi profilok.
        /// </summary>
        public static string SocialProfiles {
            get {
                return ResourceManager.GetString("SocialProfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statisztika.
        /// </summary>
        public static string Statistic {
            get {
                return ResourceManager.GetString("Statistic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hurráááá!.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szuper Adminisztrátor.
        /// </summary>
        public static string SuperAdministrator {
            get {
                return ResourceManager.GetString("SuperAdministrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cím.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visszavonás.
        /// </summary>
        public static string Unpublish {
            get {
                return ResourceManager.GetString("Unpublish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sikeresen aktiváltad fiókodat. Most már be tudsz lépni az oldalra!.
        /// </summary>
        public static string UserActivated {
            get {
                return ResourceManager.GetString("UserActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ez a felhasználó már aktiválta a fiókját..
        /// </summary>
        public static string UserAlreadyActivated {
            get {
                return ResourceManager.GetString("UserAlreadyActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Felhasználó név.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A felhasználói név már használatban van..
        /// </summary>
        public static string UsernameUsed {
            get {
                return ResourceManager.GetString("UsernameUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ilyen felhasználó nem található. Probálj meg inkább regisztrálni!.
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Felhasználók.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üdvözlet.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A jelszó nem helyes.
        /// </summary>
        public static string WrongPassword {
            get {
                return ResourceManager.GetString("WrongPassword", resourceCulture);
            }
        }
    }
}
