//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Resources.Admin {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Index {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebApplication.Resources.Admin.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Olvasott.
        /// </summary>
        public static string Checked {
            get {
                return ResourceManager.GetString("Checked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bejegyzések száma.
        /// </summary>
        public static string CountOfEntries {
            get {
                return ResourceManager.GetString("CountOfEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bejegyzések száma a hónapban.
        /// </summary>
        public static string CountOfEntriesInThisMonth {
            get {
                return ResourceManager.GetString("CountOfEntriesInThisMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email cím.
        /// </summary>
        public static string EmailAddress {
            get {
                return ResourceManager.GetString("EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Olvasottnak jelöl.
        /// </summary>
        public static string MarkRead {
            get {
                return ResourceManager.GetString("MarkRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Olvasatlannak jelöl.
        /// </summary>
        public static string MarkUnread {
            get {
                return ResourceManager.GetString("MarkUnread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üzenet.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üzenetek.
        /// </summary>
        public static string Messages {
            get {
                return ResourceManager.GetString("Messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Küldés ideje.
        /// </summary>
        public static string SendDate {
            get {
                return ResourceManager.GetString("SendDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jelenleg.
        /// </summary>
        public static string text1 {
            get {
                return ResourceManager.GetString("text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bejegyzés található a blogon!.
        /// </summary>
        public static string text2 {
            get {
                return ResourceManager.GetString("text2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ebben a hónapban.
        /// </summary>
        public static string text3 {
            get {
                return ResourceManager.GetString("text3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bejegyzés született!.
        /// </summary>
        public static string text4 {
            get {
                return ResourceManager.GetString("text4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Önnek.
        /// </summary>
        public static string text5 {
            get {
                return ResourceManager.GetString("text5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to új üzenete érkezett! (Visszajelzések).
        /// </summary>
        public static string text6 {
            get {
                return ResourceManager.GetString("text6", resourceCulture);
            }
        }
    }
}
